<html>
    <head>
        <title>Корзина</title>
        <jslib>number-input.js</jslib>
        <jslib>masked-input.js</jslib>
        <css>fill.css</css>
        <css>components/pages.css</css>
        <css>base.css</css>
        <css>basket.css</css>
        <jslib>message.js</jslib>
        <jslib>image-changer.js</jslib>
    </head>
    <body>
        <phplib>header.php</phplib>
        <php>page.php</php>
        <phplib>footer.php</phplib>
        <phplib>basket.php</phplib>
    </body>
</html>